import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { prisma } from "@/lib/prisma";

const Home: NextPage<
  Awaited<ReturnType<typeof getServerSideProps>>["props"]
> = ({ users }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="font-medium text-slate-900">
          Welcome to a simple Next JS app using a GraphQL / Prisma / MySQL
          backend
        </h1>
        <ul>
          {users &&
            users.map((user) => (
              <li key={user.id}>
                <Link href={`/user/${user.id}`}>{user.name}</Link>
              </li>
            ))}
        </ul>
      </main>
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const users = await prisma.user.findMany();

  return {
    props: {
      users,
    },
  };
}
